### ISSUE TITLE
MHT文件大于2GB时无法解析

### ISSUE THREAD

**Issue by sliots** [lqzhgood/Shmily-Get-QQ-PC_MHT#6]
我的MHT导出后文件大小是 8.63 GB (9,270,090,818 字节) 
遇到了 Node.JS 的限制

```
reMsg Time Used: 247.03618597984
Peak Memory:2049144
node:fs:403
      throw new ERR_FS_FILE_TOO_LARGE(size);
            ^

RangeError [ERR_FS_FILE_TOO_LARGE]: File size (9271939231) is greater than 2 GiB
    at tryCreateBuffer (node:fs:403:13)
    at Object.readFileSync (node:fs:456:14)
    at C:\apps\Shmily-Get-QQ-PC_MHT\index.js:31:21
    at Object.<anonymous> (C:\apps\Shmily-Get-QQ-PC_MHT\index.js:123:3)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24) {
  code: 'ERR_FS_FILE_TOO_LARGE'
}
```

**Comment by lqzhgood** [comment]
额，你这有点吓人欸。
我手上也没这么大的文件进行测试。。。。

**Comment by sliots** [comment]
原本是想借用这个项目导出json方便写入数据库，看了下 mht 的结构似乎并不复杂打算自己手搓，先关 issue 了

**Comment by lqzhgood** [comment]
那个mht对收发的显示(颜色)略有bug，你可以参考下源码里的处理
